package org.example.rpc;

public enum PermissionshipEnum {
    PERMISSIONSHIP_UNSPECIFIED,
    PERMISSIONSHIP_NO_PERMISSION,
    PERMISSIONSHIP_HAS_PERMISSION,
    PERMISSIONSHIP_CONDITIONAL_PERMISSION,
    ;
}
