server:
  port: 1111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/my_activiti?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456


spicedb:
  service:
    url: http://10.100.28.149:3331
  token: lx_token